package com.sponsoredtokens

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * WHERE THE PERSON TOKEN LIVES. One string, read and written from whatever thread asks.
 *
 * It is an interface because a token is the app's to look after: an app that already has
 * `EncryptedSharedPreferences`, a `DataStore`, or its own encrypted room can plug it in with three
 * methods and the library never learns the difference. The default is [KeystoreTokenStore].
 *
 * Every method BLOCKS. They are called from an OkHttp interceptor, which is a blocking place by
 * construction, and a store that suspended would have to be unwrapped there anyway. The suspending
 * half of the library moves them onto `Dispatchers.IO` before it touches them.
 */
public interface TokenStore {
    /** The stored value, or null. */
    public fun read(): String?

    /** Replace it. */
    public fun write(value: String)

    /** Forget it. Called on sign-out, and on any answer that says the credential is gone. */
    public fun clear()
}

/** A store that survives nothing. For tests, and for an app that deliberately keeps no token. */
public class InMemoryTokenStore : TokenStore {
    @Volatile
    private var value: String? = null

    override fun read(): String? = value
    override fun write(value: String) {
        this.value = value
    }

    override fun clear() {
        value = null
    }
}

/**
 * THE DEFAULT: AES-256-GCM under a key in the AndroidKeyStore, ciphertext in ordinary preferences.
 *
 * This is what `EncryptedSharedPreferences` does, without the dependency. That library has been in
 * alpha for years and is now deprecated, and taking an alpha into a credential path in order to use
 * a Keystore this file already has open is a dependency bought for nothing: the signing key is
 * already in the AndroidKeyStore, so the wrapping key goes in beside it.
 *
 * What it is and is not worth: the token is unreadable to anything that gets the preferences file
 * alone (an `adb backup`, a stolen disk image, another app on a rooted phone reading the data
 * directory) because the key is not in the file and cannot be exported from the hardware. It is NOT
 * proof against code running as this app, which can simply ask for the plaintext. The thing that
 * survives even that is the SIGNING key, which nothing can copy, and it is why signed calls are the
 * default whenever the connect flow gave us a device.
 */
public class KeystoreTokenStore(
    context: Context,
    private val clientId: String,
) : TokenStore {

    private val prefs = context.applicationContext.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
    private val alias = "com.sponsoredtokens.store.$clientId"

    override fun read(): String? {
        val stored = prefs.getString(clientId, null) ?: return null
        return try {
            val blob = B64.urlDecode(stored)
            // `[12 bytes of IV][ciphertext and tag]`. GCM's IV is generated by the provider on every
            // encrypt and must never be reused with one key, so it is stored beside what it made.
            if (blob.size <= IV_BYTES) return null
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, blob, 0, IV_BYTES))
            }
            String(cipher.doFinal(blob, IV_BYTES, blob.size - IV_BYTES), Charsets.UTF_8)
        } catch (_: Exception) {
            // A KEY THAT NO LONGER DECRYPTS IS A SIGN-OUT, NOT A CRASH. The Keystore drops a key when
            // the lock screen is removed, and a restored backup carries ciphertext this phone's key
            // never made. Both mean the same thing to the person: connect again.
            clear()
            null
        }
    }

    override fun write(value: String) {
        val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, key()) }
        val iv = cipher.iv
        check(iv.size == IV_BYTES) { "an unexpected GCM nonce length: ${iv.size}" }
        val blob = iv + cipher.doFinal(value.toByteArray(Charsets.UTF_8))
        prefs.edit().putString(clientId, B64.url(blob)).apply()
    }

    override fun clear() {
        prefs.edit().remove(clientId).apply()
        runCatching {
            KeyStore.getInstance(PROVIDER).apply { load(null) }.takeIf { it.containsAlias(alias) }?.deleteEntry(alias)
        }
    }

    private fun key(): SecretKey {
        val store = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (store.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        val spec = KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .setUserAuthenticationRequired(false)
            .build()
        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER).apply { init(spec) }.generateKey()
    }

    private companion object {
        const val PREFS = "com.sponsoredtokens.session"
        const val PROVIDER = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}
